@startuml CleanArchitectureExplinedByYuriGeronimus

''' Configuration
!$showExternalApi=true
!$showData=true

!$showOOBRelations=true
!$showControlFlow=false

!$showInLayers=false

!$showNotes=true
!$showLegend=true

''' Includes
!$kRepositoryRowIncUrl="https://raw.githubusercontent.com/geronimus1/clean-arch-explained/main/inc/"

!$macrosUrl=$kRepositoryRowIncUrl + "shared/macros.puml"
!$styleUrl=$kRepositoryRowIncUrl + "style/style.puml"

!$enterpriseLayerUrl=$kRepositoryRowIncUrl + "layers/enterprise.puml"
!$appplcationLayerUrl=$kRepositoryRowIncUrl + "layers/enterprise.puml"
!$interfaceLayerUrl=$kRepositoryRowIncUrl + "layers/enterprise.puml"
!$frameworksDriversLayerUrl=$kRepositoryRowIncUrl + "layers/enterprise.puml"

!$objectOrientedConnections=$kRepositoryRowIncUrl + "connections/object-oriented.puml"
!$dataConnections=$kRepositoryRowIncUrl + "connections/data.puml"
!$controlFlowConnections=$kRepositoryRowIncUrl + "connections/control-flow.puml"

!$notesUrl=$kRepositoryRowIncUrl + "additional/notes.puml"
!$legendUrl=$kRepositoryRowIncUrl + "additional/legend.puml"


!includeurl $macrosUrl
!includeurl $styleUrl

!includeurl $enterpriseLayerUrl
!includeurl $appplcationLayerUrl
!includeurl $interfaceLayerUrl
!includeurl $frameworksDriversLayerUrl

!includeurl $objectOrientedConnections
!includeurl $dataConnections
!includeurl $controlFlowConnections

!includeurl $notesUrl
!includeurl $legendUrl

''' Implementation

$setStyles()

title "Clean Architecture explained by Yuri Geronimus"

$printEnterpriseLayer($showData, $showInLayers)
$printApplicationLayer($showExternalApi, $showData, $showInLayers)
$printInterfaceLayer($showExternalApi, $showInLayers)
$printFrameworkLayer($showExternalApi, $showData, $showInLayers)

!if ($showNotes == true)
  $printNotes($showData, $showInLayers)
!endif

!if ($showControlFlow == true)
  $printControlFlow($showExternalApi)
!endif

!if ($showOOBRelations == true)
  $printObjectOrientedRelations($showExternalApi)

  !if ($showData == true)
    $printDataRelations($showExternalApi)
  !endif
!endif

!if ($showLegend == true)
  $printLegend()
  !if ($showInLayers == false)
    $CONTROLLER-[hidden]left->Legend1
  !endif
!endif

@enduml