@startuml CleanArchitectureExplinedByYuriGeronimus

'/******************************************************************************/
'/* DIAGRAM CONFIGURATION                                                      */
'/******************************************************************************/
!$showExternalApi=true
!$showData=true

!$showOOBRelations=true
!$showControlFlow=false

!$showInLayers=false

!$showNotes=true
!$showLegend=true

'/******************************************************************************/
'/* MACROS                                                                     */
'/******************************************************************************/
!$isPublished=true

!$INCLUDE_FILE="!includeurl"
!$REPOSITORY_ROW_URL="https://raw.githubusercontent.com/geronimus1/clean-arch-explained/main"

!if (false == $isPublished)
  !$REPOSITORY_ROW_URL="/Users/urijgeronimus/Documents/GitHub/clean-arch-explained/"
  !$INCLUDE_FILE="!include"
!endif

'/******************************************************************************/
'/* INCLUDES                                                                   */
'/******************************************************************************/
!$repositoryRowIncUrl=$REPOSITORY_ROW_URL+"/inc"

!$macrosUrl=$REPOSITORY_ROW_URL + "/shared/macros.puml"
!$styleUrl=$repositoryRowIncUrl + "/style/style.puml"

!$enterpriseLayerUrl=$repositoryRowIncUrl + "/layers/enterprise.puml"
!$appplcationLayerUrl=$repositoryRowIncUrl + "/layers/application.puml"
!$interfaceLayerUrl=$repositoryRowIncUrl + "/layers/interface-adapters.puml"
!$frameworksDriversLayerUrl=$repositoryRowIncUrl + "/layers/frameworks-drivers.puml"

!$objectOrientedConnections=$repositoryRowIncUrl + "/connections/object-oriented.puml"
!$dataConnections=$repositoryRowIncUrl + "/connections/data.puml"
!$controlFlowConnections=$repositoryRowIncUrl + "/connections/control-flow.puml"

!$notesUrl=$repositoryRowIncUrl + "/additional/notes.puml"
!$legendUrl=$repositoryRowIncUrl + "/additional/legend.puml"

$INCLUDE_FILE $macrosUrl

$INCLUDE_FILE $styleUrl

$INCLUDE_FILE $enterpriseLayerUrl
$INCLUDE_FILE $appplcationLayerUrl
$INCLUDE_FILE $interfaceLayerUrl
$INCLUDE_FILE $frameworksDriversLayerUrl

$INCLUDE_FILE $objectOrientedConnections
$INCLUDE_FILE $dataConnections
$INCLUDE_FILE $controlFlowConnections

$INCLUDE_FILE $notesUrl
$INCLUDE_FILE $legendUrl

'/******************************************************************************/
'/* IMPLEMENTATION                                                             */
'/******************************************************************************/
$setStyles()

title "Clean Architecture explained by Yuri Geronimus\n(https://www.linkedin.com/in/yurigeronimus/)"

$printEnterpriseLayer($showData, $showInLayers)
$printApplicationLayer($showExternalApi, $showData, $showInLayers)
$printInterfaceLayer($showExternalApi, $showInLayers)
$printFrameworkLayer($showExternalApi, $showData, $showInLayers)

!if ($showNotes == true)
  $printNotes($showData, $showInLayers)
!endif

!if ($showControlFlow == true)
  $printControlFlow($showExternalApi)
!endif

!if ($showOOBRelations == true)
  $printObjectOrientedRelations($showExternalApi)

  !if ($showData == true)
    $printDataRelations($showExternalApi)
  !endif
!endif

!if ($showLegend == true)
  $printLegend()
  !if ($showInLayers == false)
    $CONTROLLER-[hidden]left->Legend1
  !endif
!endif

@enduml