@startuml CleanArchitectureExplainedMacros

    !$PREF_INTERFACE="<<Interface>>\n"
    !$PREF_CLASS="<<Class>>\n"
    !$PREF_DATA="<<Data>>\n"
    !$PREF_API="<<API>>\n"

    !$NAME_ENT_LOGIC='Enterprise Business logic'
    !$NAME_APP_LOGIC='Application Business logic'
    !$NAME_INT_ADAPTERS='Interface Adapters'
    !$NAME_FRMWK_DRIVERS='Frameworks and drivers'

    !$NAME_RESPONSE_MODEL="ResponseModel"
    !$NAME_REQUEST_MODEL="RequestModel"
    !$NAME_API_MODEL="ResponseServiceModel"

    !$LAYER_ENT_LOGIC='"'+$NAME_ENT_LOGIC +' (Entities)"'
    !$LAYER_APP_LOGIC='"'+$NAME_APP_LOGIC +' (Use Cases)"'
    !$LAYER_INT_ADAPTERS='"'+$NAME_INT_ADAPTERS +' (Controllers, Presenters, Gateways)"'
    !$LAYER_FRMWK_DRIVERS='"'+$NAME_FRMWK_DRIVERS +' (Devices, Web, UI, External Interfaces)"'

    !$ENTITY='"'+$PREF_CLASS + "Entity"+'"'
    !$ENTITY_GATEWAY = '"'+$PREF_INTERFACE + "Entity Gateway"+'"'
    !$ENTITY_GATEWAY_IMPL = '"'+$PREF_CLASS + "Entity Gateway Implementation"+'"'
    !$OUTPUT_PORT = '"'+$PREF_INTERFACE + "Use Case Output Port"+'"'
    !$INPUT_PORT = '"'+$PREF_INTERFACE + "Use Case Input Port"+'"'
    !$EXT_API = '"'+$PREF_INTERFACE + "Use case / Service for external API"+'"'

    !$INTERACTOR = '"'+$PREF_CLASS + "Use Case Interactor"+'"'
    !$PRESENTER='"'+$PREF_CLASS + "Presenter\n(Boundary)"+'"'
    !$EXT_API_IMPL='"'+$PREF_CLASS + "Use case / Service for external API implementation\n(Boundary)"+'"'
    !$CONTROLLER='"'+$PREF_CLASS + "Controller\n(Boundary)"+'"'
    !$API_INPUT='"'+$PREF_API + "Devices, Web, External interfaces, etc"+'"'
    !$API_OUTPUT='"'+$PREF_API + "UI, External interfaces, etc"+'"'
    !$API_DATABASE='"'+$PREF_API + "DB, External interfaces, etc"+'"'

    !$DATA_REQUEST_MODEL='"'+$PREF_DATA + $NAME_REQUEST_MODEL+'"'
    !$DATA_RESPONSE_MODEL='"'+$PREF_DATA + $NAME_RESPONSE_MODEL+'"'
    !$DATA_API_MODEL='"'+$PREF_DATA + $NAME_API_MODEL+'"'
    !$DATA_ENTITY = '"'+$PREF_DATA+"Data in Entity"+'"'

    !$DATA_REQUEST = '"'+$PREF_DATA+"Request"+'"'
    !$DATA_VIEW_MODEL = '"'+$PREF_DATA+"ViewModel"+'"'
    !$DATA_EXT_API_MODEL = '"'+$PREF_DATA+"ApiModel"+'"'
    !$DATA_FOR_ENTITY = '"'+$PREF_DATA+"Data for ''Data in Entity'' construction"+'"'

    !$TYPE_DATA="<<(D,lightgrey)>>"

    !$COLOR_ENT="#FCFDB9"
    !$COLOR_APP="#FFA09C"
    !$COLOR_INTERF="#A2FDBA"
    !$COLOR_FRMWK="#A7D7FD"

    !$MSG_FLOW_CNTRL="Flow of control.\nStep #"
    !$STYLE_FLOW_CTRL="#magenta;text:magenta"

    !$STYLE_DATA_ARROW="#grey;text:grey"

@enduml